## 04 创建

In [6]:
import numpy as np

In [7]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

   ### 其他创建numpy.array的方法

#### zeros

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,5)) # The default type is float

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### ones

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### full

In [15]:
np.full((3,5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [16]:
np.full(fill_value=666, shape=(3, 5))

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

#### arange

In [18]:
np.arange? #Return evenly spaced values within a given interval.

In [20]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [21]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
[i for i in range(0, 1, 0.2)] #It can't be used with decimals

TypeError: 'float' object cannot be interpreted as an integer

In [23]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [24]:
[i for i in range(0, 10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### linspace

In [26]:
np.linspace?  #Return evenly spaced numbers over a specified interval.

In [27]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [28]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [29]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### randint

In [30]:
np.random.randint?
'''
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).
'''

In [31]:
np.random.randint(0, 10)

7

In [32]:
np.random.randint(0, 10, 10)

array([4, 5, 8, 4, 2, 9, 2, 8, 3, 3])

In [33]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
np.random.randint(0, 10, size=10)

array([4, 4, 0, 0, 4, 4, 7, 3, 9, 3])

In [35]:
np.random.randint(0, 10, size=(3,5))

array([[7, 1, 8, 9, 8],
       [6, 2, 3, 8, 5],
       [1, 1, 9, 5, 5]])

In [36]:
np.random.randint(10, size=(3, 5))

array([[0, 2, 9, 6, 7],
       [4, 9, 3, 3, 5],
       [2, 0, 1, 5, 6]])

#### seed

In [37]:
np.random.seed(666)

In [38]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [41]:
np.random.seed(666)
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

#### random

In [43]:
np.random.random()

0.8578588002246146

In [44]:
np.random.random((3,5))

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

#### normal

In [54]:
np.random.normal? 
'''
Draw random samples from a normal (Gaussian) distribution.
normal(loc=0.0, scale=1.0, size=None)
'''

SyntaxError: invalid syntax (3109851438.py, line 1)

In [45]:
np.random.normal()

0.7760516793129695

In [47]:
np.random.normal(10, 100)

128.06359754812632

In [56]:
np.random.normal(0, 1, (3, 5))

array([[ 0.06102404,  1.07856138, -0.79783572,  1.1701326 ,  0.1121217 ],
       [ 0.03185388, -0.19206285,  0.78611284, -1.69046314, -0.98873907],
       [ 0.31398563,  0.39638567,  0.57656584, -0.07019407,  0.91250436]])