## 06 numpy.array 合并和分割

In [1]:
import numpy as np

### numpy.array的合并

In [2]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [3]:
np.concatenate([x, y]) # v.连接;使连续（衔接）起来;连锁;串级

array([1, 2, 3, 3, 2, 1])

In [4]:
z = np.array([666, 666, 666])
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [5]:
A = np.array([[1, 2, 3],
             [4, 5 ,6]])
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [6]:
np.concatenate([A, A], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [7]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [8]:
np.concatenate([A, z])# There are not same shape

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [9]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [10]:
z.shape

(3,)

In [11]:
z1=z.reshape(1, -1).copy()

In [12]:
z1.shape

(1, 3)

In [13]:
A.shape

(2, 3)

In [14]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [15]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [16]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [17]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [18]:
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### numpy.array的分割

In [19]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x1, x2, x3 = np.split(x, [3, 7])

In [21]:
x1

array([0, 1, 2])

In [22]:
x2

array([3, 4, 5, 6])

In [23]:
x3

array([7, 8, 9])

In [24]:
x1, x2 = np.split(x, [5])
x1

array([0, 1, 2, 3, 4])

In [25]:
x2

array([5, 6, 7, 8, 9])

In [26]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
A1, A2 = np.split(A, [2])
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [28]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
A1, A2 = np.split(A, [2], axis = 1)
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [30]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [31]:
upper, lower = np.vsplit(A, [2])
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [32]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
left,right = np.hsplit(A, [2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [34]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [35]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
X, y = np.hsplit(data, [-1])

In [37]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [38]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [39]:
y[:, 0]

array([ 3,  7, 11, 15])