## 08 numpy中的聚合操作

### sum

In [1]:
import numpy as np

L = np.random.random(100)
sum(L)

45.15453284011157

In [2]:
np.sum(L)

45.154532840111564

In [3]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

70.3 ms ± 3.43 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
617 µs ± 17.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### min, max

In [5]:
np.min(big_array)

4.0250020016951993e-07

In [6]:
np.max(big_array)

0.9999971348744396

In [7]:
big_array.min()

4.0250020016951993e-07

In [8]:
big_array.max()

0.9999971348744396

In [9]:
big_array.sum()

499664.55003342783

### 多维度聚合

In [10]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.sum(X)

120

In [12]:
np.sum(X, axis = 0)

array([24, 28, 32, 36])

In [13]:
np.sum(X, axis = 1)

array([ 6, 22, 38, 54])

### 其他聚合操作

In [14]:
np.prod(X) #所有元素相乘

0

In [15]:
np.prod(X + 1)

2004189184

In [17]:
np.mean(X)

7.5

In [18]:
np.median(X)

7.5

In [19]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [20]:
np.median(v)

2.0

In [21]:
np.percentile(big_array, q = 50)

0.49932598703246656

In [22]:
np.median(big_array)

0.49932598703246656

In [23]:
np.percentile(big_array, q=100)

0.9999971348744396

In [24]:
np.max(big_array)

0.9999971348744396

In [25]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q = percent))

4.0250020016951993e-07
0.25021394160161947
0.49932598703246656
0.7489813586425861
0.9999971348744396


In [26]:
np.var(big_array)

0.08318058195658443

In [27]:
np.std(big_array)

0.2884104400963745

In [28]:
x = np.random.normal(0, 1, 1000000)

In [29]:
np.mean(x)

0.001304350786586329

In [30]:
np.std(x)

0.9986522908963825