## 10 Numpy中的比较和Fancy Indexing

### Fancy Indexing

In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [4]:
x[3:9:2]

array([3, 5, 7])

In [5]:
[x[3], x[5], x[7]]

[3, 5, 7]

In [6]:
ind = [3, 5, 7]
x[ind]

array([3, 5, 7])

In [7]:
ind = np.array([[0, 2], [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

### Fancy Indexing 应用在二维数组

In [8]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [10]:
X[0, col]

array([1, 2, 3])

In [11]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [12]:
col = [True, False, True, True]
X[0, col]

array([0, 2, 3])

### numpy.array的比较

In [13]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [15]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [16]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [17]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [18]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [19]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [20]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [21]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### 使用numpy.array的比较结果

In [22]:
np.count_nonzero(x <= 3)

4

In [23]:
np.sum(x <= 3)

4

In [24]:
np.sum(X % 2 == 0, axis = 0) #每列有多少个偶数

array([4, 0, 4, 0])

In [25]:
np.sum(X % 2 == 0, axis = 1) #每行有多少个偶数

array([2, 2, 2, 2])

In [26]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
np.any(x == 0)

True

In [28]:
np.any(x < 0)

False

In [29]:
np.all(x > 0)

False

In [30]:
np.all(x >= 0)

True

In [31]:
np.all(X > 0, axis=1)

array([False,  True,  True,  True])

In [32]:
np.sum((x > 3) & (x < 10))

6

In [33]:
np.sum((x > 3) && (x < 10))

SyntaxError: invalid syntax (3416034819.py, line 1)

In [34]:
np.sum((x % 2 == 0) | (x > 10))  # 0 2 4 6 8 10 11 12 13 14 15

11

In [35]:
np.sum(~(x == 0)) # ~是非的意思

15

### 比较结果和Fancy Indexing

In [37]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [39]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [40]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [41]:
X[X[:, 3]%3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])